### ISSUE TITLE
ssl support

### ISSUE THREAD

**Issue by vay3t** [rek7/postshell#1]
is it possible to add support for ssl? and that way use `ncat --ssl`

**Comment by rek7** [comment]
Its a planned feature but it's not yet added, it will also increase the size of the binary drastically as you still most likely have to statically link OpenSSL or whatever crypto lib you need. If you wish to add this feel free to make a commit!

**Comment by zero77** [comment]
@rek7 
What about loading the binary from /usr/bin/openssl or pointing it to a custom path if it's not installed,
or using `openssl s_client -quiet -connect`.
